{% set name = "papermill" %}
{% set version = "2.2.2" %}
{% set sha256 = "1c452b1c5a9ab52b94c99d8b7705ae7173f6aa88a3d28a5d30cffba48a46f5b6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  entry_points:
    - papermill = papermill.cli:papermill
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ansiwrap
    - black
    - click
    - entrypoints
    - jupyter_client
    - nbclient >=0.2.0
    - nbformat
    - pyyaml
    - requests
    - tenacity
    - tqdm >=4.32.2

test:
  imports:
    - papermill
  commands:
    - papermill --help

about:
  home: http://github.com/nteract/papermill
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Papermill parameterizes, executes, and analyzes Jupyter Notebooks
  doc_url: http://papermill.readthedocs.io
  dev_url: https://github.com/nteract/papermill
