{% set name = "papermill" %}
{% set version = "2.1.3" %}
{% set sha256 = "ecd4cafa9179693b0eedc3b6f4560f9ee47826a6e366e42bfa3cc20f7931b3f8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  entry_points:
    - papermill = papermill.cli:papermill
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ansiwrap
    - backports.tempfile
    - click
    - entrypoints
    - future
    - ipython >=5.0
    - jupyter_client
    - nbconvert >=5.5
    - nbformat
    - pandas
    - pyyaml
    - requests
    - six
    - tenacity
    - tqdm >=4.29.1

test:
  imports:
    - papermill
  commands:
    - papermill --help

about:
  home: http://github.com/nteract/papermill
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Papermill parameterizes, executes, and analyzes Jupyter Notebooks
  doc_url: http://papermill.readthedocs.io
  dev_url: https://github.com/nteract/papermill
